### ISSUE TITLE
ModuleNotFoundError: No module named 'ConfigParser'

### ISSUE THREAD

**Issue by rrjanbiah** [Kamefrede/sql2meili#2]
Apologies for posting these install issues.. but, can't get passed this error. Any hint will be helpful. TIA

<details>
  <summary>`ModuleNotFoundError: No module named 'ConfigParser'`</summary>

```
Pipfile.lock (f93fe8) out of date, updating to (448017)...
Locking [dev-packages] dependencies...
Building requirements...
Resolving dependencies...
OK Success! 
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
x Locking Failed! 
ERROR:pip.subprocessor:Command errored out with exit status 1:
 command: /root/.local/share/virtualenvs/sql2meili-master-IVF_ZTbo/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-resolver-i_az223a/mysql-python/setup.py'"'"'; __file__='"'"'/tmp/pip-resolver-i_az223a/mysql-python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-resolver-i_az223a/mysql-python/pip-egg-info
     cwd: /tmp/pip-resolver-i_az223a/mysql-python/
Complete output (7 lines):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/pip-resolver-i_az223a/mysql-python/setup.py", line 13, in <module>
    from setup_posix import get_config
  File "/tmp/pip-resolver-i_az223a/mysql-python/setup_posix.py", line 2, in <module>
    from ConfigParser import SafeConfigParser
ModuleNotFoundError: No module named 'ConfigParser'
----------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pipenv/resolver.py", line 764, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/pipenv/resolver.py", line 758, in main
    _main(parsed.pre, parsed.clear, parsed.verbose, parsed.system, parsed.write,
  File "/usr/lib/python2.7/site-packages/pipenv/resolver.py", line 741, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
  File "/usr/lib/python2.7/site-packages/pipenv/resolver.py", line 702, in resolve_packages
    results, resolver = resolve(
  File "/usr/lib/python2.7/site-packages/pipenv/resolver.py", line 684, in resolve
    return resolve_deps(
  File "/usr/lib/python2.7/site-packages/pipenv/utils.py", line 1395, in resolve_deps
    results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
  File "/usr/lib/python2.7/site-packages/pipenv/utils.py", line 1108, in actually_resolve_deps
    resolver.resolve()
  File "/usr/lib/python2.7/site-packages/pipenv/utils.py", line 823, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/usr/lib/python2.7/site-packages/pipenv/patched/piptools/resolver.py", line 180, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/lib/python2.7/site-packages/pipenv/patched/piptools/resolver.py", line 268, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "/usr/lib/python2.7/site-packages/pipenv/patched/piptools/resolver.py", line 383, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/usr/lib/python2.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 229, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/usr/lib/python2.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 350, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(
  File "/usr/lib/python2.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 306, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/usr/lib/python2.7/site-packages/pipenv/patched/notpip/_internal/legacy_resolve.py", line 339, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python2.7/site-packages/pipenv/patched/notpip/_internal/legacy_resolve.py", line 287, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/usr/lib/python2.7/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 508, in prepare_linked_requirement
    abstract_dist = _get_prepared_distribution(
  File "/usr/lib/python2.7/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 95, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/usr/lib/python2.7/site-packages/pipenv/patched/notpip/_internal/distributions/sdist.py", line 40, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/usr/lib/python2.7/site-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 564, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "/usr/lib/python2.7/site-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 538, in _generate_metadata
    return generate_metadata_legacy(
  File "/usr/lib/python2.7/site-packages/pipenv/patched/notpip/_internal/operations/build/metadata_legacy.py", line 115, in generate_metadata
    call_subprocess(
  File "/usr/lib/python2.7/site-packages/pipenv/patched/notpip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pipenv.patched.notpip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
</details>

Previously was getting `Error: pg_config executable not found.` and for that had to install `yum install postgresql12-devel` (CentOS).

**Comment by Kamefrede** [comment]
Since you're using Postgres instead of MySQL you can just remove the https://github.com/Kamefrede/sql2meili/blob/b2d9aaeb2ef72df9e106caf83aca41462836c51a/Pipfile#L14 line in the Pipfile
It happens because by default it ships with the MySQL engine and it expects you to have it installed.

**Comment by rrjanbiah** [comment]
@Kamefrede Amazing.. that's it.. thanks a lot for your quick help
